Elva and KiYong Shopping List (Redux)
rhdevs/rhdevs-frontend-training-AY2122 pull request #52
Opened 2021-10-23 15:27 UTC by kiyonggg

Done:

- Layout of page
- Add items into list (using redux)
- Delete items from list (using redux)
- Change quantity (using redux)
- Validation for adding items (only cannot add if name not included and quantity is less than 1)
<img width="1060" alt="Screenshot 2021-10-23 at 11 16 41 PM" src="https://user-images.githubusercontent.com/65106369/138562439-f2de8c85-3ad0-4039-929f-f28e60a1b567.png">

2021-10-24 11:19 UTC, xinyee20 reviewed
Package-lock.json should not be present as we are using yarn as package manager, please delete the folder. Something doesn't feel right when you see the number of lines change is 30k ++😳

2021-10-24 11:33 UTC, xinyee20 commented on src/pages/ShoppingCart4/index.tsx
> +  const [shoppingList, setShoppingList] = useState([] as ShoppingListItem[])
can be written as useState<ShoppingListItem[]>([]) where the type is written in the <>

2021-10-24 14:05 UTC, xinyee20 requested changes

2021-10-24 14:05 UTC, xinyee20 commented on src/App.tsx
> +  () => import(/* webpackChunckName: "ShoppingListsMainPage" */ './pages/ShoppingCart4'),
update the webpackChunckNames

2021-10-24 14:05 UTC, xinyee20 commented on src/App.tsx
> +      <Route path={`${PATHS.SHOPPING_PAGE_PAIR_FOUR}`} exact>
for those without additional text such as this one, can use path={PATHS.SHOPPING_PAGE_PAIR_FOUR} without the `${}`

2021-10-24 14:05 UTC, xinyee20 commented on src/store/shoppingCart4Redux/actions.ts
> +//set my 'exampleList' state with my argument 'newList'
comments can be removed:)

2021-10-24 21:15 UTC, kiyonggg commented on src/pages/ShoppingCart4/index.tsx
> +  const [shoppingList, setShoppingList] = useState([] as ShoppingListItem[])
resolved in commit 6052692

2021-10-24 21:15 UTC, kiyonggg commented on src/App.tsx
> +  () => import(/* webpackChunckName: "ShoppingListsMainPage" */ './pages/ShoppingCart4'),
resolved in commit 6052692

2021-10-24 21:15 UTC, kiyonggg commented on src/App.tsx
> +      <Route path={`${PATHS.SHOPPING_PAGE_PAIR_FOUR}`} exact>
resolved in commit 6052692

2021-10-24 21:15 UTC, kiyonggg commented on src/store/shoppingCart4Redux/actions.ts
> +//set my 'exampleList' state with my argument 'newList'
resolved in commit 6052692

2021-10-25 12:18 UTC, xinyee20 commented on src/components/AddItemModal.tsx
> +      setItemCountError('Please input a valid quantity!')
Maybe 'Please input a quantity greater than 0!' will be a better error message? Something to indicate what is valid

2021-10-25 12:27 UTC, kiyonggg commented on src/components/AddItemModal.tsx
> +      setItemCountError('Please input a valid quantity!')
resolved in commit ab913af

2021-10-25 12:32 UTC, kiyonggg commented on src/components/AddItemModal.tsx
> +      setItemCountError('Please input a valid quantity!')
resolved in commit ed6e82a

2021-10-25 13:39 UTC, xinyee20 approved these changes
Lgtm!  Make sure checks pass and conflicts are resolved before merging

2021-10-25 14:57 UTC, hui444 commented
> Lgtm!

pls make sure checks pass!!!!!!!!

2021-10-26 10:37 UTC, xinyee20 approved these changes
lgtm! Resolve conflicts before merging

2021-10-28 22:27 UTC, merged